version: 2
updates:
  - directory: /
    open-pull-requests-limit: 0
    package-ecosystem: bundler
    rebase-strategy: auto
    schedule:
      timezone: 05:00 UTC
    allow:
      - dependency-type: production